import { useQuery } from '@tanstack/react-query'
import { QRCodeSVG } from 'qrcode.react'
import type { CardTemplate } from '@/types/card'
import { resolveLabels, computeAvailableGifts } from '@/types/card'
import { StampsGrid } from '@/components/card/StampsGrid'
import { getTenant } from '@/lib/api/tenant'

interface Props {
  card: CardTemplate
  collectedStamps?: number
  customerName?: string
  /** Serial shown under the QR. Defaults to a fake preview serial. */
  serial?: string
}

/**
 * Visual mockup of how this card looks inside Apple Wallet on iPhone.
 *
 * Mirrors the actual `.pkpass` we generate in
 * `api/app/Services/Wallet/Apple/ApplePassBuilder.php` 1:1, including
 * the directional behavior of every region observed on a real iOS pass:
 *
 *   - Header row: logo box + card name on the LEFT (as a single group),
 *     stamps headerField on the RIGHT. The title is NOT centred — it
 *     hugs the logo, matching how Apple Wallet renders our pkpass.
 *
 *   - Apple Wallet keeps `headerFields` and `secondaryFields` in array
 *     order with **LTR** layout regardless of the iPhone's language —
 *     so for Arabic content, `secondaryFields[0]` (المكافأة) sits on
 *     the LEFT and `[1]` (العميل) on the RIGHT.
 *
 *   - The strip image is RTL — `ApplePassBuilder::generateStripImage`
 *     bakes stamp #1 on the right edge and progresses leftwards. The
 *     preview wraps that island in `dir="rtl"` while the rest of the
 *     pass is `dir="ltr"`.
 *
 *   - All text uses `colors.foreground` at full opacity. Apple Wallet
 *     does NOT dim labels — labels and values share the same color, the
 *     label is just smaller.
 */
export function ApplePassPreview({
  card,
  collectedStamps = 3,
  customerName = 'أحمد محمد',
  serial = 'PREVIEW-XXXX',
}: Props) {
  const { design, rewards } = card
  const stampsRequired = rewards[0]?.stampsRequired ?? design.stampsCount
  const labels = resolveLabels(design.labels)
  // Brand logo from /admin/settings — single source of truth.
  const { data: tenant } = useQuery({
    queryKey: ['tenant'],
    queryFn: getTenant,
    staleTime: 60_000,
  })
  const brandLogo = design.logoUrl || tenant?.logo || null
  // Title fallback chain mirrors ApplePassBuilder::resolveLabel():
  //   1. design.labels.title  (rare per-card override)
  //   2. card.name            (canonical Arabic card name)
  //   3. tenant.name          (brand name from /admin/settings)
  const displayTitle = labels.title || card.name || tenant?.name || ''
  // GIFT counter — available redemptions, shown in the headerField
  // opposite the logo. Matches Alpha Spa's pass layout exactly.
  const availableGifts = computeAvailableGifts(collectedStamps, stampsRequired)

  return (
    <div
      dir="ltr"
      className="rounded-[14px] overflow-hidden shadow-2xl flex flex-col"
      style={{
        background: design.colors.background,
        color: design.colors.foreground,
      }}
    >
      {/* Header bar — logo + optional title on the LEFT, GIFT
          headerField on the RIGHT (matching the Alpha Spa pkpass
          screenshot). Logo sizing follows Apple's official store-card
          rule: ≤ 160 × 50 px at 1×. The display title is optional —
          when empty, only the logo + GIFT counter render. */}
      <div className="flex items-center justify-between px-4 pt-4 pb-3 gap-3">
        <div className="flex items-center gap-3 min-w-0 flex-1">
          {brandLogo && (
            <img
              src={brandLogo}
              alt=""
              className="object-contain shrink-0 max-h-[30px] max-w-[96px]"
            />
          )}
          {displayTitle && (
            <div
              className="text-sm truncate min-w-0 flex-1"
              style={{ color: design.colors.foreground }}
            >
              {displayTitle}
            </div>
          )}
        </div>
        <div className="text-right shrink-0">
          <div className="text-[11px] font-medium leading-tight mb-0.5">
            {labels.reward}
          </div>
          <div className="text-sm tabular-nums leading-tight">
            {availableGifts}
          </div>
        </div>
      </div>

      {/* Strip area — RTL island so stamp #1 sits on the right edge,
          matching the pkpass image generated by ApplePassBuilder. */}
      <div dir="rtl" className="px-3">
        <StampsGrid
          design={design}
          collectedStamps={collectedStamps}
          rounded="0.5rem"
        />
      </div>

      {/* Secondary fields — stamps (left), customer (right). LTR order
          matches Apple Wallet's actual rendering for Arabic passes.
          The reward field was removed per user request. */}
      <div className="flex justify-between px-4 pt-4 pb-4 gap-3">
        <div className="text-left min-w-0 flex-1">
          <div className="text-[11px] font-medium leading-tight mb-0.5">{labels.stamps}</div>
          <div className="text-sm truncate">
            {collectedStamps}/{stampsRequired}
          </div>
        </div>
        <div className="text-right min-w-0 flex-1">
          <div className="text-[11px] font-medium leading-tight mb-0.5">{labels.customer}</div>
          <div className="text-sm truncate">{customerName}</div>
        </div>
      </div>

      {/* QR barcode — narrow white tile hugging QR + serial, centered
          inside the pass body. NOT a full-width banner: matches the
          way Apple Wallet renders the barcode card on a real iPhone. */}
      <div className="px-4 pb-4 flex justify-center">
        <div className="inline-flex flex-col items-center bg-white rounded-md p-3 gap-2">
          <QRCodeSVG value={serial} size={108} level="M" />
          <div className="text-[11px] text-neutral-700 tracking-wider font-mono">
            {serial}
          </div>
        </div>
      </div>
    </div>
  )
}
